### ISSUE TITLE
where to put files?

### ISSUE THREAD

**Issue by tarbear123** [respeaker/respeaker_arduino_library#3]
do i put all the files into a folder in my arduino library?

**Comment by per1234** [comment]
Easiest and least prone to error installation method:

1. Download https://github.com/respeaker/respeaker_arduino_library/archive/master.zip
2. (In the Arduino IDE) Sketch > Include Library > Add .ZIP Library > select the downloaded file > Open

**Comment by tarbear123** [comment]
thx

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
